scenario_env_json: data/ds_1.json
output_path: outputs/ds_1_v2 # absolute path
lgsvl_map: 12da60a7-2fc9-474d-a62a-5cc08cb97fe8
apollo_map: San Francisco Correct

pop_size: 4
npc_size: 2
time_size: 10
bounds: [[0, 30], [0, 3]]
total_sim_time: 30
p_mutation: 0.4
p_crossover: 0.4
max_gen: 100
# selection: roulette
selection: top

# apollo reltaed path config
default_record_folder: /home/victor/Desktop/apollo/data/bag # False means ignoring records